### ISSUE TITLE
Get task name from RunToken

### ISSUE THREAD

**Issue by wackazong** [antialize/tokio-tasks#1]
Hi there, just tried out your library and it works beautifully. Many thanks! Say, it would be great to have the task name available from the RunToken, then you can access it in the actual function that is being run. Would that be possible? If you give me some pointers I could do a PR. Thanks!

**Comment by antialize** [comment]
Hi wackazong. There is no one to one relationship between run tokens and tasks. The same run token may be shared between multiple tasks, and a single task may use several different run tokens. That being said, in practice a task has one "primary" run token, and the vast majority of run tokens are attached to exactly one task.

I think a reasonable way to implement what you want is to also store a name in a RunToken, as Cow<'static, str>.

An outline for a pr implementing this would be.

For `RunToken`:
- Add a `name: Cow<'static, str>` field.
- Change the new to store the empty name.
- Add a `with_name(name: impl Into<Cow<'static, str>>) -> Self` constructer .
- add a `pub fn name(&self) -> &str`, accessor.

For `TaskBuilder`:
- Change the type of the `run_token` field to `Option<RunToken>`
- Update set_run_token to store a `Some(run_token)`
- Change the run_token access in create to `self.run_token.unrwap_or_else(|| RunToken::with_name(self.name.clone())`

**Comment by wackazong** [comment]
Ok, thanks for the explanation. I see your point about the n:n relationship, then ist does not make sense for me to add this feature.
